<?php

declare(strict_types=1);

namespace Syntexa\Orm\Attributes;

use Attribute;
use Syntexa\Core\Attributes\DocumentedAttributeInterface;
use Syntexa\Core\Attributes\DocumentedAttributeTrait;

/**
 * Marks an identifier property as auto-generated by the database
 * 
 * @see DocumentedAttributeInterface
 */
#[Attribute(Attribute::TARGET_PROPERTY)]
class GeneratedValue implements DocumentedAttributeInterface
{
    use DocumentedAttributeTrait;

    public readonly ?string $doc;

    public const STRATEGY_AUTO = 'auto';
    public const STRATEGY_NONE = 'none';

    public function __construct(
        ?string $doc = null,
        public string $strategy = self::STRATEGY_AUTO
    ) {
        $this->doc = $doc;
    }

    public function getDocPath(): string
    {
        return $this->doc ?? 'docs/en/attributes/GeneratedValue.md';
    }
}


